FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y \
	libopencv-dev \
        python3-pip \
	python3-opencv && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt /opt/requirements.txt

WORKDIR /opt
RUN pip3 install -r requirements.txt --default-timeout=100 

WORKDIR /
COPY run_jupyter.sh /

RUN chmod +x run_jupyter.sh

RUN ["mkdir", "src"]
RUN ["mkdir", "src/notebooks"]
RUN ["mkdir", "src/models"]
RUN ["mkdir", "src/data"]
RUN ["mkdir", "src/output"]
COPY conf/.jupyter /root/.jupyter


# Jupyter and Tensorboard ports
EXPOSE 8889 6006

# Store notebooks in this mounted directory
VOLUME src/notebooks

# Store models in this mounted directory
VOLUME src/models

# Store datasets in this mounted directory
VOLUME src/data

# Store models output in this mounted directory
VOLUME src/output

CMD ["/run_jupyter.sh"]
